// <auto-generated />
namespace FeedForSites.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class minlen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(minlen));
        
        string IMigrationMetadata.Id
        {
            get { return "201307061742353_min-len"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
