// <auto-generated />
namespace FeedForSites.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class minleng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(minleng));
        
        string IMigrationMetadata.Id
        {
            get { return "201307061739490_min-leng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
