// <auto-generated />
namespace FeedForSites.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MessageConversationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageConversationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201302132100400_Message-ConversationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
